---
cloud_service_group: SQLServers
cloud_service_type: Server
name: Count By Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
  filter:
    - key: account
      value: true
      operator: exists
options:
  chart_type: DONUT
