---
cloud_service_group: Snapshots
cloud_service_type: Instance
name: Snapshots Count by Resource Group
query:
  aggregate:
   - group:
       keys:
        - name: name
          key: data.resource_group
       fields:
        - name: value
          key: data.resource_group
          operator: count
options:
  chart_type: DONUT
