from .advisor import *
from .application_gatways import *
from .cognitive_services import *
from .container_instances import *
from .container_registries import *
from .cosmos_db import *
from .disks import *
from .key_vaults import *
from .load_balancers import *
from .my_sql_servers import *
from .mysql_sql_flexible_servers import *
from .nat_gateways import *
from .network_security_groups import *
from .postgre_sql_flexible_servers import *
from .postgre_sql_servers import *
from .public_ip_addresses import *
from .public_ip_prefiexes import *
from .service_health import *
from .snapshots import *
from .sql_databases import *
from .sql_servers import *
from .storage_accounts import *
from .virtual_machines import *
from .virtual_networks import *
from .vm_scale_sets import *
from .web_pub_sub_service import *
from .functions import *
